### ISSUE TITLE
[FEAT] Create a custom authentication page 

### ISSUE THREAD

**Issue by cb7chaitanya** [code100x/tiplink#158]

**Comment by dhruv-colosus** [comment]
Hey is it to change the next auth customisation page UI ? If so can you assign this to me

**Comment by cb7chaitanya** [comment]
Yes, the next auth default page, we want to create our own custom UI

**Comment by dhruv-colosus** [comment]
I have a doubt. The current auth is google one which is directly linked to the landing page . 
So which page is needed to be customised ? 

Do I have to create a new page at /signin with just google auth or should the UI include email password as well ? Can you please elaborate so that I can start working on it asap

**Comment by cb7chaitanya** [comment]
You can refer to the next auth documentation on how we create custom authentication pages 
Also, we are sticking to google provider for now

**Comment by dhruv-colosus** [comment]
@cb7chaitanya #159 Creates this new page. Let me know if this is what you wanted
