### ISSUE TITLE
Login with Google Button not working

### ISSUE THREAD

**Issue by Parikshit2001** [code100x/tiplink#24]
For me "login with Google" button is not working
Someone please comment down below if its working for you,
do comment down and let me know if it is not working also

**Comment by maniksharma17** [comment]
Does it lead to /signup page?

**Comment by Parikshit2001** [comment]
The solution is to get rid of the Link component.

**Comment by cb7chaitanya** [comment]
I got rid of it, it is showing another 302 error, working on that right now

**Comment by Parikshit2001** [comment]
Its working for me

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@cb7chaitanya this sign in works as usual but  create-post route dosent exists thats it 
sign in with google is working though

![image](https://github.com/user-attachments/assets/5b0d8c22-fd00-4a82-8ef4-eb6223f42205)

**Comment by maniksharma17** [comment]
When I signin, I get this error. Could anyone help me with it?

<img width="1053" alt="Screenshot 2024-08-05 at 2 03 01 PM" src="https://github.com/user-attachments/assets/7e0cc3b3-8b66-4549-9a39-0945465065ba">
<img width="1470" alt="Screenshot 2024-08-05 at 2 04 57 PM" src="https://github.com/user-attachments/assets/ae56a86f-e889-4ad3-aee9-2caea48fc7cc">

**Comment by Allan2000-Git** [comment]
Check your environment variables

**Comment by Praashh** [comment]
Guys it's working, since in lib/auth.js we have added a custom page for api/auth/sign to /signin, 

if you comment it
 ![image](https://github.com/user-attachments/assets/99fa34ab-f161-4f46-a1c4-6ba59584a17b) 

and try again it'll work 
![image](https://github.com/user-attachments/assets/5c5be20e-4d3a-4eb3-a714-773e2df36e62)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@Praashh so will we use the next auth page default page for signin ?
Or we will create a signin page by own and use it

**Comment by Praashh** [comment]
> @Praashh so will we use the next auth page default page for signin ? Or we will create a signin page by own and use it

we just need a button, not a separate signing page, try to explore tiplink to understand the working.

**Comment by Riya267** [comment]
Hey @cb7chaitanya  this issue is not related to google provider , this is issue from database adapter (prisma) being used in auth.ts. Seems like Database schema was not pushed properly to the database which was creating issues.
To resolve this, just run:
npx prisma generate
npx prisma db push 

and this will fix this issue 

https://github.com/user-attachments/assets/275a1728-b2f3-420c-937f-60eea4bd8036

**Comment by cb7chaitanya** [comment]
Closing this issue, marked as already fixed

**Comment by cb7chaitanya** [comment]
Closed
